Repository side-peek/sidepeek_frontend, pull requests merged in 2024-03, with the labels that each got.

#63 [Feature/#62/HeaderStyle] 헤더 디자인 속성 개선
  src/components/Header/Header.tsx
  src/styles/theme.ts
Labels: Design, Refactor

#73 [Feat ✏️] InputBox 구성 컴포넌트 및 InputBoxMain 컴포넌트 생성
  src/components/InputBox/InputBox.tsx
  src/components/InputBox/components/InputContent.tsx
  src/components/InputBox/components/InputFooter.tsx
  src/components/InputBox/components/InputHeader.tsx
Labels: Feat, Urgent

#58 [Feature/#2/login page] 로그인 페이지 UI
  src/components/Header/Header.tsx
  src/components/LogoLink/LogoLink.tsx
  src/pages/LoginPage/LoginPage.tsx
  src/pages/LoginPage/components/BackButton.tsx
  src/pages/LoginPage/components/CreateAccount.tsx
  src/pages/LoginPage/components/LoginForm/LoginForm.tsx
  src/pages/LoginPage/components/LoginForm/components/LoginButton.tsx
  src/pages/LoginPage/components/LoginForm/components/LoginFormLabel.tsx
  src/pages/LoginPage/components/SocialLogin.tsx
Labels: Design, Feat, Not Yet

#59 [Feature/#47/project form] 프로젝트 작성 form Text 관련 Input 부분 구현
  src/pages/ProjectEditPage/components/ProjectEditForm.tsx
  src/pages/ProjectEditPage/components/ProjectInputBox.tsx
  src/pages/ProjectEditPage/constants/defaultValues.ts
  src/pages/ProjectEditPage/constants/registerOptions.ts
  src/pages/ProjectEditPage/types/ProjectFormValues.ts
Labels: Feat, Not Yet

#77 [Feature/#76/Footer] 푸터 컴포넌트 구현
  src/components/Footer/Footer.tsx
  src/styles/layouts/DefaultLayout.tsx
  src/styles/theme.ts
Labels: Design

#67 [Feature/#52/ ProjectDetail/skill] 프로젝트 상세정보(스킬,기간)
  src/api/project/getProjectDetail.ts
  src/assets/images/noImage.jpg
  src/mocks/auth/postEmailLogin.mock.ts
  src/pages/ProjectDetailPage/ProjectDetailPage.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailContent/ProjectDetailContent.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailContent/ProjectDetailDate/ProjectDetailDate.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailContent/ProjectDetailMembers/ProjectDetailMembers.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailContent/ProjectDetailTechStacks/ProjectDetailTechStacks.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailSummary/ProjectDetailSummary.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailSummary/ProjectDetailSummaryContent/ProjectDetailSummaryContent.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailSummary/ProjectDetailSummaryContent/ProjectDetailSummaryLeft.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailSummary/ProjectDetailSummaryContent/ProjectDetailSummaryLink.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailSummary/ProjectDetailSummaryContent/ProjectDetailSummaryLinkButton.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailSummary/ProjectDetailSummaryContent/ProjectDetailSummaryRight.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailSummary/ProjectDetailSummaryContent/ProjectDetailSummaryRightIcon.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailSummary/ProjectDetailSummaryContent/ProjectDetailSummaryText.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailSummary/ProjectDetailSummaryTitle/ProjectDetailSummaryTitle.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailSummary/ProjectDetailSummaryTop/ProjectDetailSummaryTop.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailSummary/ProjectDetailSummaryTop/ProjectDetailSummaryTopIcon.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailSummary/ProjectDetailSummaryTop/ProjectDetailSummaryTopIconButton.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailTabList.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailTabList/ProjectDetailTabItem.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailTabList/ProjectDetailTabList.tsx
  src/pages/ProjectDetailPage/hooks/queries/useProjectDetailQuery.ts
  src/pages/ProjectDetailPage/mocks/mockData.ts
  src/pages/ProjectDetailPage/utils/changeDateForm.ts
  src/pages/ProjectDetailPage/utils/getGroupedCategory.ts
  src/types/domain/apiDomain.d.ts
Labels: Design, Feat

#57 [Feature/#41/ProfilePage] 프로필 페이지 UI 구현
  src/mocks/handlers.ts
  src/pages/ProfilePage/LargeScreenView/LargeScreen.view.tsx
  src/pages/ProfilePage/ProfilePage.tsx
  src/pages/ProfilePage/SmallScreenView/SmallScreen.view.tsx
  src/pages/ProfilePage/components/Profile/Profile.controller.tsx
  src/pages/ProfilePage/components/Profile/Profile.model.ts
  src/pages/ProfilePage/components/Profile/ProfileActionsButtons.tsx
  src/pages/ProfilePage/components/Profile/ProfileBar.view.tsx
  src/pages/ProfilePage/components/Profile/ProfileCard.tsx
  src/pages/ProfilePage/components/Profile/ProfileIntroduction.tsx
  src/pages/ProfilePage/components/Profile/ProfileTechStack.tsx
  src/pages/ProfilePage/components/Profile/ProfileTechStackByCategory.tsx
  src/pages/ProfilePage/components/Projects/Projects.model.ts
  src/pages/ProfilePage/components/Projects/Projects.view.tsx
  src/pages/ProfilePage/components/Projects/ProjectsCommented.tsx
  src/pages/ProfilePage/components/Projects/ProjectsLiked.tsx
  src/pages/ProfilePage/components/Projects/ProjectsOwned.tsx
  src/pages/ProfilePage/mocks/index.ts
  src/pages/ProfilePage/mocks/mockData.ts
  src/pages/ProfilePage/styles/StyledProfileActionButton.tsx
  src/pages/ProfilePage/styles/StyledProfileBarBox.tsx
  src/pages/ProfilePage/styles/StyledProfileBarContainer.tsx
  src/pages/ProfilePage/styles/StyledProfileCardBox.tsx
  src/pages/ProfilePage/styles/StyledTab.tsx
  src/pages/ProfilePage/types/types.ts
  src/styles/theme.ts
  src/types/domain/apiDomain.d.ts
Labels: Design, Feat

#70 [Feature/#69/ ProjectMembers] 프로젝트 상세정보(멤버)
  src/api/project/getProjectDetail.ts
  src/pages/ProjectDetailPage/ProjectDetailPage.tsx
  src/pages/ProjectDetailPage/components/Content/Content.tsx
  src/pages/ProjectDetailPage/components/Content/Date/Date.tsx
  src/pages/ProjectDetailPage/components/Content/Explanation/Explanation.tsx
  src/pages/ProjectDetailPage/components/Content/Explanation/ExplanationItem.tsx
  src/pages/ProjectDetailPage/components/Content/MemberInfo/MemberCard/MemberCard.tsx
  src/pages/ProjectDetailPage/components/Content/MemberInfo/MemberInfo.tsx
  src/pages/ProjectDetailPage/components/Content/MemberInfo/MemberList/MemberList.tsx
  src/pages/ProjectDetailPage/components/Content/TechStacks/TechStacks.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailContent/ProjectDetailContent.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailContent/ProjectDetailMembers/ProjectDetailMembers.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailSummary/ProjectDetailSummaryContent/ProjectDetailSummaryLeft.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailSummary/ProjectDetailSummaryContent/ProjectDetailSummaryText.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailTabList/ProjectDetailTabList.tsx
  src/pages/ProjectDetailPage/components/Summary/Summary.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryContent/SummaryContent.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryContent/SummaryLeft.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryContent/SummaryLink.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryContent/SummaryLinkButton.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryContent/SummaryOverview.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryContent/SummaryRight.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryContent/SummaryRightIcon.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryTitle/SummaryTitle.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryTop/SummaryTop.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryTop/SummaryTopIcon.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryTop/SummaryTopIconButton.tsx
  src/pages/ProjectDetailPage/mocks/mockData.ts
  src/pages/ProjectDetailPage/utils/membersCategory.ts
  src/pages/ProjectDetailPage/utils/techStacksCategory.ts
  src/types/domain/apiDomain.d.ts
Labels: Design, Feat

#85 [Fix/#84/FixFooterLayout] footer 컴포넌트로 인한 레이아웃 변경으로 UI 깨지는 현상 수정
  src/pages/ProfilePage/components/Profile/Profile.controller.tsx
  src/styles/layouts/DefaultLayout.tsx
Labels: Design, HotFix

#87 [Feat ✏️] 공통 버튼 스타일의 background, hover시 background 속성 제거
  src/pages/ProjectDetailPage/components/Summary/SummaryTop/SummaryTopIcon.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryTop/SummaryTopIconButton.tsx
  src/styles/theme.ts
Labels: Design

#65 [Feature/#31/getUserInfo] 유저 정보 프리패칭 (라우터 관련 로직 포함)
  src/App.tsx
  src/api/auth/getEmailAuth.ts
  src/api/auth/postEmailLogin.ts
  src/components/PreFetcher/Prefetcher.tsx
  src/constants/endPoints.ts
  src/constants/queryKey.ts
  src/mocks/auth/getEmailAuth.mock.ts
  src/mocks/auth/postEmailLogin.mock.ts
  src/mocks/auth/postEmailRefresh.mock.ts
  src/mocks/handlers.ts
  src/routes/index.tsx
  src/routes/loaders/determineRedirectLoader.ts
  src/services/caches/useUserInfoData.ts
  src/services/queries/userInfoOptions.ts
  src/types/domain/apiDomain.d.ts
  tsconfig.json
Labels: Feat, Not Yet

#93 [feature/#392/ErrorMessage] ErrorMessage 컴포넌트
  src/components/ErrorMessage/ErrorMessage.tsx
  src/components/ErrorMessage/types/ErrorMessageProps.ts
Labels: Feat, Minor

#82 [Feature/#71/ProjectDetail/Comment] 프로젝트 상세정보(댓글)
  .eslintrc.cjs
  package-lock.json
  package.json
  src/api/axiosInstance.ts
  src/api/comment/deleteComment.ts
  src/api/comment/editComment.ts
  src/api/comment/postComment.ts
  src/components/Input/CommonInput.tsx
  src/constants/endPoints.ts
  src/pages/ProjectDetailPage/ProjectDetailPage.tsx
  src/pages/ProjectDetailPage/components/Comments/Comments.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsAvatar.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsButton.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsForm.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsInputOrText.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsList.tsx
  src/pages/ProjectDetailPage/components/Comments/EditingButton.tsx
  src/pages/ProjectDetailPage/components/Comments/Hoc/withProjectId.tsx
  src/pages/ProjectDetailPage/components/Comments/Layout/CommentsLayout.tsx
  src/pages/ProjectDetailPage/components/Comments/OwnerButton.tsx
  src/pages/ProjectDetailPage/components/Comments/ReplyComment.tsx
  src/pages/ProjectDetailPage/components/Content/TechStacks/TechStacks.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryContent/SummaryLink.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryContent/SummaryRight.tsx
  src/pages/ProjectDetailPage/hooks/mutations/useDeleteCommentMutation.ts
  src/pages/ProjectDetailPage/hooks/mutations/useEditCommentMutation.ts
  src/pages/ProjectDetailPage/hooks/mutations/usePostCommentMutation.ts
  src/pages/ProjectDetailPage/hooks/queries/useProjectDetailQuery.ts
  src/pages/ProjectDetailPage/mocks/index.ts
  src/pages/ProjectDetailPage/mocks/mockData.ts
  src/pages/ProjectDetailPage/types/commentFormValues.ts
  src/pages/ProjectDetailPage/utils/datetoTimeago.ts
  src/types/domain/apiDomain.d.ts
Labels: Design, Feat, Refactor, Rename

#83 [Refactor/#74/skill search] 프로젝트 작성 Form 기술스택 필드 추가
  src/api/skill/getSearchTechStacks.ts
  src/components/Search/SearchContainer.tsx
  src/components/Search/SearchMain.tsx
  src/components/Search/components/SearchBar.tsx
  src/components/Search/components/SearchFetcher.tsx
  src/components/Search/components/SearchLayout.tsx
  src/components/Search/components/SearchResult.tsx
  src/components/Search/hooks/queries/useGetTechStacksQuery.ts
  src/components/Search/hooks/queries/useSearchQuery.ts
  src/components/Search/hooks/useSearch.ts
  src/components/Search/hooks/useTechStacksSearch.ts
  src/components/Search/mocks/mockData.ts
  src/components/Search/stores/SearchContext/SearchContext.ts
  src/components/Search/stores/useSearchContext.tsx
  src/constants/queryKey.ts
  src/mocks/handlers.ts
  src/pages/ProjectEditPage/components/ProjectEditForm.tsx
  src/pages/ProjectEditPage/components/ProjectForm.tsx
  src/pages/ProjectEditPage/components/TechStacksFields/TechStackFields.tsx
  src/pages/ProjectEditPage/components/TechStacksFields/components/StackSearchBox.tsx
  src/pages/ProjectEditPage/constants/defaultValues.ts
  src/pages/ProjectEditPage/constants/registerOptions.ts
  src/pages/ProjectEditPage/hooks/useTechStacksFieldsArray.ts
  src/pages/ProjectEditPage/types/ProjectFormValues.ts
  src/types/domain/apiDomain.d.ts
Labels: Feat

#90 [Refactor/#88/custom label] Tag 컴포넌트 리팩토링
  src/components/Tag/components/CloseButtonTag.tsx
  src/components/Tag/components/CommonTag.tsx
  src/components/Tag/components/CustomTag.tsx
  src/components/Tag/types/commonTagProps.ts
  src/components/Tag/types/customTag.ts
  src/pages/ProfilePage/components/Profile/ProfileTechStackByCategory.tsx
  src/pages/ProjectDetailPage/components/Content/TechStacks/TechStacks.tsx
Labels: Design, Feat, Refactor, Minor

#96 [Fix 🪛] CloseButtonTag의 props 타입오류 수정
  src/components/Tag/components/CloseButtonTag.tsx
  src/pages/ProjectEditPage/components/TechStacksFields/components/StackSearchBox.tsx
Labels: HotFix, Urgent, Minor

#75 [feature/#61/ProfileEditPage] 프로필 수정 페이지 UI 구현
  src/pages/ProfileEditPage/ProfileEditPage.tsx
  src/pages/ProfileEditPage/components/Modal/ChangeNicknameModal.tsx
  src/pages/ProfileEditPage/components/Modal/ChangePWModal.tsx
  src/pages/ProfileEditPage/components/Profile/ProfileCard.tsx
  src/pages/ProfileEditPage/components/Profile/ProfileIntroduction.tsx
  src/pages/ProfileEditPage/components/Profile/ProfileTechStack.tsx
  src/pages/ProfileEditPage/constants/validation.ts
  src/pages/ProfileEditPage/styles/StyledButton.tsx
  src/pages/ProfileEditPage/types/types.ts
  src/routes/index.tsx
Labels: Design, Feat

#91 [feature/#89/pagination] 페이지네이션 구현
  src/components/Pagination/Pagination.tsx
  src/components/Pagination/components/NextButton/NextButton.tsx
  src/components/Pagination/components/PageButtons/PageButtons.tsx
  src/components/Pagination/components/PrevButton/PrevButton.tsx
  src/components/Pagination/constants/constants.ts
  src/components/Pagination/stores/contexts.tsx
  src/components/Pagination/styles/moveButtonStyles.ts
  src/components/Pagination/styles/pageButtonStyles.ts
  src/components/Pagination/types/types.ts
Labels: Design, Feat

#105 [hotfix/#104/CorsError] cors 에러 우회를 위한 proxy 설정
  vite.config.ts
Labels: Feat, HotFix

#103 [hotfix/#102/UserInfo] 유저 정보 저장 로직 수정
  src/App.tsx
  src/api/auth/postEmailAuth.ts
  src/api/auth/postEmailRefresh.ts
  src/api/axiosInstance.ts
  src/constants/customError.ts
  src/constants/endPoints.ts
  src/mocks/auth/postEmailAuth.mock.ts
  src/mocks/auth/postEmailRefresh.mock.ts
  src/mocks/handlers.ts
  src/services/caches/useUserInfoData.ts
  src/services/queries/userInfoOptions.ts
  src/stores/authToken.ts
  src/types/domain/apiDomain.d.ts
Labels: HotFix, Refactor, Urgent

#99 [Feature/#80/ProjectDetail/reply] 대댓글 및 댓글 로직 리팩토링
  src/api/comment/deleteComment.ts
  src/api/comment/editComment.ts
  src/api/comment/postComment.ts
  src/constants/endPoints.ts
  src/mocks/auth/postEmailAuth.mock.ts
  src/mocks/auth/postEmailLogin.mock.ts
  src/mocks/auth/postEmailRefresh.mock.ts
  src/pages/HomePage/HomePage.tsx
  src/pages/ProjectDetailPage/components/Comments/Comments.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsAvatar.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsButton.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsForm.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsForm/CommentsForm.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsInputOrText.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/CommentsItem.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/components/BeforeEditingButton.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/components/CommentTitle.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/components/CommentsAvatar.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/components/CommentsEditFormText.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/components/OnEditingButton.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/components/ReplyComment.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsList.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsList/CommentsList.tsx
  src/pages/ProjectDetailPage/components/Comments/Layout/CommentsLayout.tsx
  src/pages/ProjectDetailPage/components/Comments/OwnerButton.tsx
  src/pages/ProjectDetailPage/components/Comments/ReplyComment.tsx
  src/pages/ProjectDetailPage/components/Content/Explanation/Explanation.tsx
  src/pages/ProjectDetailPage/components/Content/Explanation/ExplanationItem.tsx
  src/pages/ProjectDetailPage/components/Content/MemberInfo/MemberCard/MemberCard.tsx
  src/pages/ProjectDetailPage/components/Content/MemberInfo/MemberList/MemberList.tsx
  src/pages/ProjectDetailPage/components/Content/TechStacks/TechStacks.tsx
  src/pages/ProjectDetailPage/hooks/mutations/useDeleteCommentMutation.ts
  src/pages/ProjectDetailPage/hooks/mutations/useEditCommentMutation.ts
  src/pages/ProjectDetailPage/hooks/mutations/usePostCommentMutation.ts
  src/pages/ProjectDetailPage/mocks/mockData.ts
  src/pages/ProjectDetailPage/store/CommentContext.tsx
  src/pages/ProjectDetailPage/types/commentContextProps.ts
  src/pages/ProjectDetailPage/types/commentFormValues.ts
  src/pages/ProjectDetailPage/utils/membersCategory.ts
  src/pages/ProjectDetailPage/utils/techStacksCategory.ts
  src/types/domain/apiDomain.d.ts
  vite.config.ts
  vite.config.ts.timestamp-1710225043987-09395ec3e8644.mjs
Labels: Feat, Refactor

#109 [feature/#68/authorization] 인증 관련 에러핸들링
  src/App.tsx
  src/api/axiosInstance.ts
  src/components/ErrorBoundary/AuthErrorBoundary/AuthErrorBoundary.tsx
  src/components/ErrorBoundary/AuthErrorBoundary/components/ConfirmModal.tsx
  src/components/ErrorBoundary/ErrorBoundaries.tsx
  src/components/LoadingComponents/FullScreenSpinner.tsx
  src/components/PreFetcher/Prefetcher.tsx
  src/hooks/useLogout.ts
  src/mocks/auth/postEmailLogin.mock.ts
  src/mocks/auth/postEmailRefresh.mock.ts
  src/pages/TestPage/TestPage.tsx
  src/routes/index.tsx
  src/routes/layouts/DefaultLayout.tsx
  src/routes/layouts/RootLayout.tsx
  src/routes/loaders/determineRedirectLoader.ts
  src/services/queries/userInfoOptions.ts
  src/utils/isAuthError.ts
  src/utils/isAxios401Error.ts
Labels: Feat

#98 [Feature/#97/AvatarCard] AvatarCard 컴포넌트
  src/components/AvatarCard/AvatarCard.tsx
  src/components/AvatarCard/Components/AvatarCardContent.tsx
  src/components/AvatarCard/Components/AvatarCardHeader.tsx
  src/components/AvatarCard/Components/AvatarCardImage.tsx
Labels: Design, Feat, Urgent

#110 [Feature/#101/postFile] 파일 업로드 관련 custom hook 추가
  src/api/projectFile/postProjectFiles.ts
  src/mocks/handlers.ts
  src/pages/ProjectEditPage/hooks/useFileUpload.ts
  src/pages/ProjectEditPage/hooks/usePostFileMutation.ts
  src/pages/ProjectEditPage/mocks/index.ts
  src/pages/ProjectEditPage/types/FileUploadStateType.ts
  src/pages/ProjectEditPage/types/PostFormDataType.ts
  src/pages/ProjectEditPage/types/TypedFormDataValue.ts
Labels: Feat, Not Yet

#119 [hotfix/#116/PermissionError] 인증 api가 아닌 다른 요청에서 401에러를 받는 경우 권한 에러를 생성
  src/api/axiosInstance.ts
Labels: HotFix

#117 [feature/#30/SignUpPage] 회원가입 페이지
  src/api/like/deleteLike.ts
  src/api/user/postDoubleCheckEmail.ts
  src/api/user/postDoubleCheckNickname.ts
  src/api/user/postEmailSignUp.ts
  src/components/BackButton/BackButton.tsx
  src/components/InputController/InputController.tsx
  src/components/InputController/types/InputControllerProps.ts
  src/components/InputController/types/fieldNames.ts
  src/constants/queryKey.ts
  src/mocks/auth/postEmailAuth.mock.ts
  src/mocks/handlers.ts
  src/pages/LoginPage/LoginPage.tsx
  src/pages/LoginPage/components/LoginForm/LoginForm.tsx
  src/pages/LoginPage/components/LoginForm/components/LoginFormLabel.tsx
  src/pages/LoginPage/constants/registerOptions.ts
  src/pages/LoginPage/types/LoginFormType.ts
  src/pages/ProjectDetailPage/hooks/mutations/useDeleteLikeMutation.ts
  src/pages/ProjectDetailPage/hooks/mutations/usePostLikeMutation.ts
  src/pages/ProjectEditPage/hooks/usePostFileMutation.ts
  src/pages/SignUpPage/SignUpPage.tsx
  src/pages/SignUpPage/components/LoginLink.tsx
  src/pages/SignUpPage/components/SignUpForm/SignUpForm.tsx
  src/pages/SignUpPage/components/SignUpForm/components/DoubleCheckButton.tsx
  src/pages/SignUpPage/components/SignUpForm/components/SignUpButton.tsx
  src/pages/SignUpPage/components/SocialSignUp.tsx
  src/pages/SignUpPage/constants/errorOptions.ts
  src/pages/SignUpPage/constants/registerOptions.ts
  src/pages/SignUpPage/constants/toastMessages.ts
  src/pages/SignUpPage/constants/toastOptions.ts
  src/pages/SignUpPage/hooks/mutations/useDoubleCheckEmailMutation.ts
  src/pages/SignUpPage/hooks/mutations/useDoubleCheckNicknameMutation.ts
  src/pages/SignUpPage/hooks/mutations/useSignUpMutation.ts
  src/pages/SignUpPage/hooks/useSignUpForm.ts
  src/pages/SignUpPage/mocks/postDoubleCheckEmail.mock.ts
  src/pages/SignUpPage/mocks/postDoubleCheckNickname.mock.ts
  src/pages/SignUpPage/mocks/postEmailSignUp.mock.ts
  src/pages/SignUpPage/types/DoubleCheckProps.ts
  src/pages/SignUpPage/types/SignUpFormValues.ts
  src/services/caches/useUserInfoData.ts
  src/services/queries/userInfoOptions.ts
  src/types/domain/apiDomain.d.ts
  tsconfig.json
Labels: Feat

#128 [Hotfix/settings] apis 폴더 절대경로 수정에 따른 폴더명 및 import 경로 수정
  src/apis/auth/githubLogin.ts
  src/apis/auth/postEmailAuth.ts
  src/apis/auth/postEmailLogin.ts
  src/apis/auth/postEmailRefresh.ts
  src/apis/axiosInstance.ts
  src/apis/comment/deleteComment.ts
  src/apis/comment/editComment.ts
  src/apis/comment/postComment.ts
  src/apis/like/deleteLike.ts
  src/apis/like/postLike.ts
  src/apis/project/deleteProject.ts
  src/apis/project/getAllProjects.ts
  src/apis/project/getProjectDetail.ts
  src/apis/project/postProject.ts
  src/apis/project/putProject.ts
  src/apis/projectFile/postProjectFiles.ts
  src/apis/skill/getSearchTechStacks.ts
  src/apis/user/getUserDetail.ts
  src/apis/user/getUserProjects.ts
  src/apis/user/getUserSummary.ts
  src/apis/user/postDoubleCheckEmail.ts
  src/apis/user/postDoubleCheckNickname.ts
  src/apis/user/postEmailSignUp.ts
  src/apis/user/putUserDetail.ts
  src/apis/user/putUserPassword.ts
  src/components/Search/hooks/queries/useGetTechStacksQuery.ts
  src/pages/HomePage/hooks/queries/useAllProjectQuery.ts
  src/pages/ProfilePage/components/Profile/Profile.model.ts
  src/pages/ProfilePage/components/Projects/Projects.model.ts
  src/pages/ProjectDetailPage/hooks/mutations/useDeleteCommentMutation.ts
  src/pages/ProjectDetailPage/hooks/mutations/useEditCommentMutation.ts
  src/pages/ProjectDetailPage/hooks/mutations/usePostCommentMutation.ts
  src/pages/ProjectDetailPage/hooks/queries/useProjectDetailQuery.ts
  src/pages/SignUpPage/hooks/mutations/useDoubleCheckEmailMutation.ts
  src/types/domain/apiDomain.d.ts
  tsconfig.json
Labels: HotFix, Refactor, Urgent

#130 Feature/#114/project detail/like
  src/apis/project/getProjectDetail.ts
  src/pages/ProjectDetailPage/components/Comments/CommentsForm/CommentsForm.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/components/CommentsEditFormText.tsx
  src/pages/ProjectDetailPage/components/Summary/Summary.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryTop/SummaryTop.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryTop/SummaryTopIcon.tsx
  src/pages/ProjectDetailPage/hooks/mutations/useDeleteLikeMutation.ts
  src/pages/ProjectDetailPage/hooks/mutations/usePostCommentMutation.ts
  src/pages/ProjectDetailPage/hooks/mutations/usePostLikeMutation.ts
  src/pages/ProjectDetailPage/mocks/mockData.ts
  src/types/domain/apiDomain.d.ts
Labels: Feat

#122 [Feature/#47/team] 팀원 검색 컴포넌트
  package-lock.json
  package.json
  src/apis/user/getUserListByNickname.ts
  src/apis/user/getUserSummary.ts
  src/components/Search/SearchMain.tsx
  src/components/Search/components/SearchResult.tsx
  src/pages/ProjectEditPage/ProjectEditPage.tsx
  src/pages/ProjectEditPage/components/Files/FileUploadBox.tsx
  src/pages/ProjectEditPage/components/Files/FileUploadSection.tsx
  src/pages/ProjectEditPage/components/Files/Overview.tsx
  src/pages/ProjectEditPage/components/Files/Thumbnail.tsx
  src/pages/ProjectEditPage/components/MemberFields/MemberFields.tsx
  src/pages/ProjectEditPage/components/MemberFields/components/UserListFetcher.tsx
  src/pages/ProjectEditPage/components/MemberFields/components/UserSearchBox.tsx
  src/pages/ProjectEditPage/components/MemberFields/hooks/useGetUserListByNickname.ts
  src/pages/ProjectEditPage/components/MemberFields/hooks/useMemberFieldsMethods.ts
  src/pages/ProjectEditPage/components/ProjectForm.tsx
  src/pages/ProjectEditPage/constants/defaultValues.ts
  src/pages/ProjectEditPage/constants/registerOptions.ts
  src/pages/ProjectEditPage/hooks/useFileUpload.ts
  src/pages/ProjectEditPage/mocks/index.ts
  src/pages/ProjectEditPage/mocks/mockData.ts
  src/pages/ProjectEditPage/types/ProjectFormValues.ts
  src/routes/index.tsx
  src/types/domain/apiDomain.d.ts
Labels: Feat

#124 [feature/#120/HandleHeaderLogin] 헤더 로그인, 로그아웃 기능 구현
  src/components/Header/Header.tsx
  src/components/Header/components/HeaderContainer.tsx
  src/components/Header/components/LoginButton.tsx
  src/components/Header/components/Menu.tsx
  src/components/Header/components/Menu/Menu.tsx
  src/components/Header/components/Menu/components/NotificationPopover/NotificationPopover.tsx
  src/components/Header/components/Menu/components/NotificationPopover/components/NotificationIconButton.tsx
  src/components/Header/components/Menu/components/ProfilePopover/ProfilePopover.tsx
  src/components/Header/components/Menu/components/ProfilePopover/components/CreateProjectButton.tsx
  src/components/Header/components/Menu/components/ProfilePopover/components/LogoutButton.tsx
  src/components/Header/components/Menu/components/ProfilePopover/components/ProfileButton.tsx
  src/components/Header/components/Menu/components/ProfilePopover/components/ProfileEditButton.tsx
  src/components/Header/components/Menu/components/ProfilePopover/components/ProfileLink.tsx
  src/components/Header/components/ProfilePopover.tsx
  src/components/Header/constants/messages.ts
  src/mocks/auth/postEmailLogin.mock.ts
  src/pages/LoginPage/LoginPage.tsx
  src/pages/LoginPage/components/LoginForm/LoginForm.tsx
  src/pages/LoginPage/components/LoginForm/components/LoginButton.tsx
  src/pages/LoginPage/constants/toastMessages.ts
  src/pages/LoginPage/hooks/mutations/useLoginMutation.ts
  src/pages/LoginPage/hooks/useLoginForm.ts
Labels: Feat

#126 [Refactor/#125/RemoveLodash] lodash의 isFunction을 typeof로 대체
  src/components/InputController/InputController.tsx
Labels: Refactor

#107 [Featrue/#79/fix home page] 홈페이지 수정 + 더보기, 무한스크롤
  package-lock.json
  package.json
  src/apis/project/getAllProjects.ts
  src/apis/project/getBannerProjects.ts
  src/assets/images/sidepeek_blue.png
  src/components/ProjectCard/ProjectCard.tsx
  src/constants/endPoints.ts
  src/constants/queryKey.ts
  src/mocks/handlers.ts
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/components/Banner/Banner.tsx
  src/pages/HomePage/components/MoreButton/MoreButton.tsx
  src/pages/HomePage/components/ProjectList/ProjectList.tsx
  src/pages/HomePage/components/ProjectListSection/ProjectListSection.tsx
  src/pages/HomePage/hooks/queries/useAllProjectQuery.ts
  src/pages/HomePage/hooks/queries/useBannerProjectQuery.ts
  src/pages/HomePage/mocks/index.ts
  src/pages/HomePage/mocks/mockData.ts
  src/pages/HomePage/types/type.ts
  src/types/domain/apiDomain.d.ts
Labels: Feat, Refactor

#132 [Feature/#121/ProjectDetail/error] 댓글/좋아요 요청에 대한 에러처리 / 엣지 케이스 처리 / 반응형 수정
  src/constants/endPoints.ts
  src/pages/ProjectDetailPage/ProjectDetailPage.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsForm/CommentsForm.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/components/CommentsEditFormText.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsList/CommentsList.tsx
  src/pages/ProjectDetailPage/components/Content/Content.tsx
  src/pages/ProjectDetailPage/components/Content/Date/Date.tsx
  src/pages/ProjectDetailPage/components/Content/Explanation/ExplanationItem.tsx
  src/pages/ProjectDetailPage/components/Content/MemberInfo/MemberInfo.tsx
  src/pages/ProjectDetailPage/components/Content/TechStacks/TechStacks.tsx
  src/pages/ProjectDetailPage/components/Summary/Summary.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryContent/SummaryLeft.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryContent/SummaryOverview.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryContent/SummaryRight.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryTitle/SummaryTitle.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryTop/SummaryTop.tsx
  src/pages/ProjectDetailPage/constants/toastMessage.ts
  src/pages/ProjectDetailPage/hooks/mutations/useDeleteCommentMutation.ts
  src/pages/ProjectDetailPage/hooks/mutations/useDeleteLikeMutation.ts
  src/pages/ProjectDetailPage/hooks/mutations/useEditCommentMutation.ts
  src/pages/ProjectDetailPage/hooks/mutations/usePostCommentMutation.ts
  src/pages/ProjectDetailPage/hooks/mutations/usePostLikeMutation.ts
  src/pages/ProjectDetailPage/hooks/queries/useProjectDetailQuery.ts
  src/pages/ProjectDetailPage/store/CommentContext.tsx
Labels: Feat, Refactor

#131 [Feature] 기술스택 컴포넌트 리팩토링
  src/components/TechStack/TechStackSection.tsx
  src/components/TechStack/hooks/useTechStack.ts
  src/pages/ProjectEditPage/components/Files/Overview.tsx
  src/pages/ProjectEditPage/components/Files/Thumbnail.tsx
  src/pages/ProjectEditPage/components/TechStacksFields/components/StackSearchBox.tsx
  src/pages/ProjectEditPage/constants/defaultValues.ts
  src/pages/ProjectEditPage/constants/registerOptions.ts
  src/pages/ProjectEditPage/types/ProjectFormValues.ts
Labels: HotFix, Urgent

#137 [fix/#136/AllProjectListApi] getAllProject 헤더에 토큰 추가
  src/apis/project/getAllProjects.ts
Labels: Feat, Refactor

#138 [Feature/#40/project list page] 검색 결과 페이지
  src/components/Input/CommonInput.tsx
  src/components/Input/types/types.ts
  src/components/ProjectList/ProjectList.tsx
  src/pages/HomePage/components/ProjectListSection/ProjectListSection.tsx
  src/pages/ProjectListPage/ProjectListPage.tsx
  src/pages/ProjectListPage/components/ResultInfo.tsx
  src/pages/ProjectListPage/components/SearchSection.tsx
Labels: Design, Feat

#148 [refactor/#134/ProfileEditPage]
  src/pages/ProfileEditPage/ProfileEditPage.tsx
  src/pages/ProfileEditPage/components/Modal/ChangeNicknameModal.tsx
  src/pages/ProfileEditPage/components/Modal/ChangePWModal.tsx
  src/pages/ProfileEditPage/components/Modal/ChangeProfileImageModal.tsx
  src/pages/ProfileEditPage/components/Profile/ProfileCard.tsx
  src/pages/ProfileEditPage/components/Profile/ProfileTechStack.tsx
  src/pages/ProfileEditPage/hooks/mutation/usePutUserDetailMutation.ts
  src/pages/ProfileEditPage/hooks/mutation/usePutUserPassword.ts
  src/pages/ProfileEditPage/hooks/useFileUpload.ts
  src/pages/ProfileEditPage/types/types.ts
  src/pages/ProfilePage/components/Profile/Profile.controller.tsx
  src/pages/ProfilePage/components/Profile/ProfileActionsButtons.tsx
  src/pages/ProfilePage/components/Profile/ProfileBar.view.tsx
  src/pages/ProfilePage/components/Profile/ProfileIntroduction.tsx
  src/pages/ProfilePage/components/Profile/ProfileTechStack.tsx
  src/pages/ProfilePage/components/Profile/ProfileTechStackByCategory.tsx
Labels: HotFix, Minor

#145 [Refactor/project form] 프로젝트 작성 페이지 리팩토링
  src/components/TechStack/TechStackSection.tsx
  src/pages/ProfileEditPage/components/Profile/ProfileTechStack.tsx
  src/pages/ProjectEditPage/components/Editors/Description.tsx
  src/pages/ProjectEditPage/components/Editors/components/UpdateIcon.tsx
  src/pages/ProjectEditPage/components/FieldContainer.tsx
  src/pages/ProjectEditPage/components/MemberFields/MemberFields.tsx
  src/pages/ProjectEditPage/components/MemberFields/components/UserListFetcher.tsx
  src/pages/ProjectEditPage/components/MemberFields/components/UserSearchBox.tsx
  src/pages/ProjectEditPage/components/MemberFields/hooks/useMemberFieldsMethods.ts
  src/pages/ProjectEditPage/components/ProjectForm.tsx
  src/pages/ProjectEditPage/components/TechStacksFields/TechStackFields.tsx
  src/pages/ProjectEditPage/constants/defaultValues.ts
  src/pages/ProjectEditPage/constants/registerOptions.ts
  src/pages/ProjectEditPage/hooks/usePostProjectMutation.ts
  src/pages/ProjectEditPage/stores/ProjectFormProvider.tsx
  src/pages/ProjectEditPage/types/ProjectFormValues.ts
  src/pages/ProjectEditPage/utils/filterSelectedId.test.ts
  src/pages/ProjectEditPage/utils/filterSelectedId.ts
  src/pages/ProjectEditPage/utils/filterSelectedStack.ts
  src/types/domain/apiDomain.d.ts
Labels: Feat

#144 [feature/#140/UncaughtErrorBoundary] 전역 에러 바운더리 구현
  src/components/ErrorBoundary/AuthErrorBoundary/AuthErrorBoundary.tsx
  src/components/ErrorBoundary/ErrorBoundaries.tsx
  src/components/ErrorBoundary/UncaughtErrorBoundary/UncaughtErrorBoundary.tsx
  src/components/ErrorBoundary/UncaughtErrorBoundary/components/UncaughtFallback.tsx
Labels: Feat

#143 [feature/#139/HeaderSearch] 헤더 검색 로직 구현
  src/components/Header/Header.tsx
Labels: Feat

#151 [Fix 🪛] 홈, 검색 버그
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/components/Banner/Banner.tsx
  src/pages/HomePage/components/ProjectListSection/ProjectListSection.tsx
  src/pages/ProfilePage/components/Projects/ProjectsGrid.tsx
  src/pages/ProjectListPage/ProjectListPage.tsx
  src/pages/ProjectListPage/components/SearchBarSection/SearchBarSection.tsx
Labels: HotFix

#154 [hotfix/#153/CatchLogoutError] AuthErrorBoundary가 로그아웃 에러를 처리할 수 있도록 수정
  src/components/ErrorBoundary/AuthErrorBoundary/AuthErrorBoundary.tsx
Labels: HotFix

#155 [feature/#123/GitHubSocialLogin] 깃헙 소셜 로그인
  src/apis/auth/getGithubLogin.ts
  src/apis/auth/postEmailAuth.ts
  src/constants/endPoints.ts
  src/constants/externalLinks.ts
  src/constants/queryKey.ts
  src/pages/LoginPage/components/SocialLogin.tsx
  src/pages/NicknameSetupPage/NicknameSetupPage.tsx
  src/pages/NicknameSetupPage/components/AlertModal.tsx
  src/pages/NicknameSetupPage/components/NicknameInput.tsx
  src/pages/NicknameSetupPage/components/SubmitButton.tsx
  src/pages/NicknameSetupPage/constants/toastMessages.ts
  src/pages/NicknameSetupPage/hooks/query/useGithubLoginQuery.ts
  src/pages/NicknameSetupPage/hooks/useNicknameSetup.ts
  src/pages/SignUpPage/components/SignUpForm/SignUpForm.tsx
  src/pages/SignUpPage/components/SignUpForm/components/DoubleCheckButton.tsx
  src/pages/SignUpPage/components/SignUpForm/components/InputWithDoubleCheck.tsx
  src/pages/SignUpPage/components/SocialSignUp.tsx
  src/pages/SignUpPage/constants/toastMessages.ts
  src/pages/SignUpPage/hooks/mutations/useDoubleCheckEmailMutation.ts
  src/pages/SignUpPage/hooks/mutations/useDoubleCheckMutation.ts
  src/pages/SignUpPage/hooks/mutations/useDoubleCheckNicknameMutation.ts
  src/pages/SignUpPage/hooks/useDoubleCheck.ts
  src/pages/SignUpPage/hooks/useSignUpForm.ts
  src/pages/SignUpPage/types/DoubleCheckProps.ts
  src/pages/SignUpPage/types/doubleCheckFieldNames.ts
  src/routes/index.tsx
  src/stores/useDoubleCheckStore.ts
  src/types/domain/apiDomain.d.ts
Labels: Feat, Refactor

#159 [reafctor/projectDetail/] 프로젝트 상세정보 리팩토링
  src/pages/ProjectDetailPage/ProjectDetailPage.tsx
  src/pages/ProjectDetailPage/components/Comments/Comments.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsForm/CommentsForm.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/CommentsItem.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/components/BeforeEditingButton.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/components/CommentsEditForm.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/components/CommentsEditFormText.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/components/CommentsText.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/components/ReplyComment.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsList/CommentsList.tsx
  src/pages/ProjectDetailPage/components/Content/TechStacks/TechStacks.tsx
  src/pages/ProjectDetailPage/components/DeleteCheckModal.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryContent/SummaryLink.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryTop/SummaryTop.tsx
  src/pages/ProjectDetailPage/constants/scrollBarNone.ts
  src/pages/ProjectDetailPage/constants/toastMessage.ts
  src/pages/ProjectDetailPage/hooks/mutations/useDeleteCommentMutation.ts
  src/pages/ProjectDetailPage/hooks/mutations/useEditCommentMutation.ts
  src/pages/ProjectDetailPage/hooks/mutations/usePostCommentMutation.ts
  src/pages/ProjectDetailPage/hooks/mutations/usePostLikeMutation.ts
  src/pages/ProjectDetailPage/store/CommentContext.tsx
  src/pages/ProjectDetailPage/types/commentContextFormProps.ts
  src/pages/ProjectDetailPage/types/commentContextProps.ts
  src/pages/ProjectDetailPage/utils/techStacksCategory.ts
Labels: Refactor

#167 [refactor/#166/ProfileEditPage]
  src/components/Search/components/SearchBar.tsx
  src/components/Search/hooks/queries/useGetTechStacksQuery.ts
  src/components/Search/hooks/useTechStacksSearch.ts
  src/components/TechStack/TechStackSection.tsx
  src/pages/ProfileEditPage/ProfileEditPage.tsx
  src/pages/ProfileEditPage/components/Profile/ProfileIntroduction.tsx
  src/pages/ProfileEditPage/constants/validation.ts
  src/pages/ProfileEditPage/types/types.ts
  src/pages/ProjectEditPage/components/TechStacksFields/components/StackSearchBox.tsx
Labels: Refactor

#169 [reafctor/projectDetail] 프로젝트 상세정보 리팩토링2
  src/pages/ProjectDetailPage/components/Comments/Comments.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsForm/CommentsForm.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/CommentsItem.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/components/BeforeEditingButton.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/components/CommentTitle.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/components/CommentsAvatar.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/components/CommentsEditForm.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/components/OnEditingButton.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsList/CommentsList.tsx
  src/pages/ProjectDetailPage/components/Content/Content.tsx
  src/pages/ProjectDetailPage/components/Content/Explanation/ExplanationItem.tsx
  src/pages/ProjectDetailPage/components/Content/Member/Member.tsx
  src/pages/ProjectDetailPage/components/Content/Member/MemberList/MemberList.tsx
  src/pages/ProjectDetailPage/components/Content/MemberInfo/MemberCard/MemberCard.tsx
  src/pages/ProjectDetailPage/components/Content/TechStacks/TechStacks.tsx
  src/pages/ProjectDetailPage/components/DeleteCheckModal.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryContent/SummaryRightIcon.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryTop/SummaryControl.tsx
  src/pages/ProjectDetailPage/constants/textAreaStyle.ts
  src/pages/ProjectDetailPage/hooks/mutations/usePostCommentMutation.ts
  src/pages/ProjectDetailPage/types/commentsProps.ts
  src/pages/ProjectDetailPage/utils/categorizeMembers.ts
  src/pages/ProjectDetailPage/utils/datetoTimeago.ts
  src/pages/ProjectDetailPage/utils/membersCategory.ts
  src/pages/ProjectDetailPage/utils/techStacksCategory.ts
  src/styles/theme.ts
  src/utils/categorizeTechStacks.ts
Labels: Refactor

#164 Refactor/#150/project rewrite
  src/apis/project/postProject.ts
  src/apis/project/putProject.ts
  src/pages/ProjectEditPage/ProjectEditPage.tsx
  src/pages/ProjectEditPage/components/DefaultValueFetcher.tsx
  src/pages/ProjectEditPage/components/Editors/Description.tsx
  src/pages/ProjectEditPage/components/Files/FileUploadBox.tsx
  src/pages/ProjectEditPage/components/Files/FileUploadSection.tsx
  src/pages/ProjectEditPage/components/Files/Overview.tsx
  src/pages/ProjectEditPage/components/Files/Thumbnail.tsx
  src/pages/ProjectEditPage/components/MemberFields/MemberFields.tsx
  src/pages/ProjectEditPage/components/MemberFields/hooks/useMemberFieldsMethods.ts
  src/pages/ProjectEditPage/components/ProjectForm.tsx
  src/pages/ProjectEditPage/components/ProjectInputBox.tsx
  src/pages/ProjectEditPage/components/TechStacksFields/TechStackFields.tsx
  src/pages/ProjectEditPage/components/TechStacksFields/hooks/useTechStacksMethods.ts
  src/pages/ProjectEditPage/components/styles/FieldContainer.tsx
  src/pages/ProjectEditPage/constants/defaultValues.ts
  src/pages/ProjectEditPage/constants/registerOptions.ts
  src/pages/ProjectEditPage/hooks/useFileUpload.ts
  src/pages/ProjectEditPage/hooks/useGetProject.ts
  src/pages/ProjectEditPage/hooks/usePostFileMutation.ts
  src/pages/ProjectEditPage/hooks/usePostProjectMutation.ts
  src/pages/ProjectEditPage/hooks/usePutProjectMutation.ts
  src/pages/ProjectEditPage/stores/ProjectFormProvider.tsx
  src/pages/ProjectEditPage/utils/convertedMembers.ts
  src/pages/ProjectEditPage/utils/parseProjectDetail.ts
  src/types/domain/apiDomain.d.ts
Labels: Feat

#172 [Change 🚜 ] 파일 위치 변경으로 인한 오류 수정
  src/pages/ProjectDetailPage/components/Content/Member/Member.tsx
  src/pages/ProjectEditPage/components/MemberFields/MemberFields.tsx
  src/pages/ProjectEditPage/components/MemberFields/hooks/useMemberFieldsMethods.ts
  src/pages/ProjectEditPage/constants/defaultValues.ts
  src/pages/ProjectEditPage/stores/ProjectFormProvider.tsx
  src/pages/ProjectEditPage/types/ProjectFormValues.ts
  src/pages/ProjectEditPage/utils/parseProjectDetail.ts
  src/utils/categorizeMembers.ts
  src/utils/process/processMembers.test.ts
  src/utils/process/processMembers.ts
  src/utils/process/processTechStacks.test.ts
  src/utils/process/processTechStacks.ts
Labels: HotFix, Minor

#171 [Refactor/#168] 버그 수정 및 리팩토링
  src/App.tsx
  src/components/Footer/Footer.tsx
  src/components/Header/Header.tsx
  src/components/Header/components/Menu/components/ProfilePopover/ProfilePopover.tsx
  src/components/Header/components/Menu/components/ProfilePopover/components/LogoutButton.tsx
  src/components/Header/components/Menu/components/ProfilePopover/components/LogoutModal.tsx
  src/constants/externalLinks.ts
  src/pages/SignUpPage/constants/registerOptions.ts
  src/routes/index.tsx
  src/routes/loaders/determineRedirectLoader.ts
Labels: Deploy, Refactor

#176 [hotfix/#175] query string 깨짐 현상 수정
  src/apis/auth/getGithubLogin.ts
Labels: HotFix

#177 [Hotfix/#175] query string 깨짐 현상 수정
  src/apis/auth/getGithubLogin.ts
Labels: HotFix

#179 Refactor/#170/profile edit page
  src/components/TechStack/TechStackSection.tsx
  src/pages/ProfilePage/LargeScreenView/LargeScreen.view.tsx
  src/pages/ProfilePage/SmallScreenView/SmallScreen.view.tsx
  src/pages/ProfilePage/components/Profile/Profile.controller.tsx
  src/pages/ProfilePage/components/Profile/ProfileBar.view.tsx
  src/pages/ProfilePage/components/Profile/ProfileCard.tsx
Labels: Design, Minor

#178 [Refactor/#156/home and list page] 기술스택 필터링 + 코드 리팩토링
  src/apis/project/getAllProjects.ts
  src/components/ProjectFilter/ProjectFilter.tsx
  src/components/ProjectList/ProjectList.tsx
  src/components/TechStackFilter/TechStackFilter.tsx
  src/pages/HomePage/components/ProjectListSection/ProjectListSection.tsx
  src/pages/HomePage/hooks/queries/useAllProjectQuery.ts
  src/pages/ProjectListPage/ProjectListPage.tsx
  src/stores/useSkillStore.ts
  src/types/domain/apiDomain.d.ts
Labels: Design, Feat, Refactor

#180 [Refactoring ⚙️] react-hook-form -> zustand로 리팩토링
  src/pages/ProjectEditPage/components/Editors/Description.tsx
  src/pages/ProjectEditPage/components/MemberFields/MemberFields.tsx
  src/pages/ProjectEditPage/components/MemberFields/components/UserSearchBox.tsx
  src/pages/ProjectEditPage/components/MemberFields/hooks/useMemberFieldsMethods.ts
  src/pages/ProjectEditPage/components/MemberFields/stores/useMemberStore.ts
  src/pages/ProjectEditPage/components/ProjectForm.tsx
  src/pages/ProjectEditPage/components/TechStacksFields/TechStackFields.tsx
  src/pages/ProjectEditPage/components/TechStacksFields/components/Field.tsx
  src/pages/ProjectEditPage/components/TechStacksFields/hooks/useTechStacksMethods.ts
  src/pages/ProjectEditPage/constants/defaultValues.ts
  src/pages/ProjectEditPage/stores/ProjectFormProvider.tsx
  src/pages/ProjectEditPage/types/ProjectFormValues.ts
  src/pages/ProjectEditPage/utils/convert/convertDate.ts
  src/pages/ProjectEditPage/utils/convert/convertMembersData.ts
  src/pages/ProjectEditPage/utils/convert/convertTechStacksData.ts
  src/pages/ProjectEditPage/utils/convertedMembers.ts
  src/stores/useTechStackStore.ts
Labels: Feat

#181 [Reafctor/projectDetail] members/techstacks 데이터 형식 변경에 따른 수정
  src/pages/ProjectDetailPage/components/Comments/CommentsForm/CommentsForm.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/CommentsItem.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/components/ReplyButton.tsx
  src/pages/ProjectDetailPage/components/Content/Member/Member.tsx
  src/pages/ProjectDetailPage/components/Content/Member/MemberList/MemberList.tsx
  src/pages/ProjectDetailPage/components/Content/TechStacks/TechStacks.tsx
  src/types/domain/apiDomain.d.ts
  src/utils/categorizeMembers.ts
  src/utils/categorizeTechStacks.ts
Labels: Refactor

#184 서버 데이터 변경으로 인한 에러 수정
  src/components/Search/hooks/queries/useGetTechStacksQuery.ts
  src/pages/ProfileEditPage/hooks/useExample.ts
  src/pages/ProfilePage/components/Profile/ProfileCard.tsx
  src/pages/ProjectEditPage/components/DefaultValueFetcher.tsx
  src/pages/ProjectEditPage/components/MemberFields/MemberFields.tsx
  src/pages/ProjectEditPage/components/MemberFields/components/UserSearchBox.tsx
  src/pages/ProjectEditPage/components/MemberFields/stores/useMemberStore.ts
  src/pages/ProjectEditPage/components/TechStacksFields/TechStackFields.tsx
  src/pages/ProjectEditPage/components/TechStacksFields/components/Field.tsx
  src/pages/ProjectEditPage/hooks/useGetProject.ts
  src/pages/ProjectEditPage/stores/ProjectFormProvider.tsx
  src/pages/ProjectEditPage/types/ProjectFormValues.ts
  src/pages/ProjectEditPage/utils/convert/convertMembersData.ts
  src/pages/ProjectEditPage/utils/convert/convertTechStacksData.ts
  src/pages/ProjectEditPage/utils/filterSelectedId.ts
  src/pages/ProjectEditPage/utils/parseProjectDetail.ts
  src/stores/useTechStackStore.ts
  src/utils/process/processMembers.test.ts
  src/utils/process/processMembers.ts
  src/utils/process/processTechStacks.test.ts
  src/utils/process/processTechStacks.ts
Labels: HotFix

#185 [Refactor/#156/home and list page] 더보기, 무한스크롤 로직 수정
  src/apis/project/getAllProjects.ts
  src/components/TechStackFilter/TechStackFilter.tsx
  src/pages/HomePage/components/ProjectListSection/ProjectListSection.tsx
  src/pages/HomePage/hooks/queries/useAllProjectQuery.ts
  src/pages/ProjectListPage/ProjectListPage.tsx
  src/types/domain/apiDomain.d.ts
Labels: Feat, HotFix, Refactor

#189 [Refactor/#187/ServiceDeploy] 서비스 배포를 위한 리팩토링
  src/components/ErrorBoundary/UncaughtErrorBoundary/components/UncaughtFallback.tsx
  src/components/Header/components/Menu/components/ProfilePopover/components/LogoutButton.tsx
  src/components/InputController/types/fieldNames.ts
  src/components/ProjectList/ProjectList.tsx
  src/components/TechStackFilter/TechStackFilter.tsx
  src/hooks/useLogout.ts
  src/pages/HomePage/HomePage.tsx
  src/pages/ProfileEditPage/ProfileEditPage.tsx
  src/pages/ProfilePage/ProfilePage.tsx
  src/pages/ProjectDetailPage/ProjectDetailPage.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryTop/SummaryControl.tsx
  src/pages/ProjectEditPage/ProjectEditPage.tsx
  src/pages/ProjectEditPage/components/Files/FileUploadBox.tsx
  src/pages/ProjectEditPage/components/Files/FileUploadSection.tsx
  src/pages/ProjectEditPage/components/Files/Overview.tsx
  src/pages/ProjectEditPage/components/Files/Thumbnail.tsx
  src/pages/ProjectEditPage/components/ProjectForm.tsx
  src/pages/ProjectEditPage/stores/ProjectFormProvider.tsx
  src/pages/ProjectListPage/ProjectListPage.tsx
  src/pages/ProjectListPage/components/ResultInfo/ResultInfo.tsx
  src/pages/ProjectListPage/components/SearchBarSection/SearchBarSection.tsx
  src/pages/SignUpPage/hooks/useDoubleCheck.ts
  src/services/caches/useUserInfoData.ts
  src/types/domain/apiDomain.d.ts
Labels: Deploy, Refactor

#190 [reafctor/projectDetail] 프로젝트 상세정보 리팩토링 및 자동 스크롤 추가
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/CommentsItem.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/components/ReplyButton.tsx
  src/pages/ProjectDetailPage/components/Content/Date/Date.tsx
  src/pages/ProjectDetailPage/components/Content/Explanation/Explanation.tsx
  src/pages/ProjectDetailPage/components/Content/Explanation/ExplanationItem.tsx
  src/pages/ProjectDetailPage/components/Content/Member/Member.tsx
  src/pages/ProjectDetailPage/components/Content/Member/MemberList/MemberList.tsx
  src/pages/ProjectDetailPage/components/Content/TechStacks/TechStacks.tsx
  src/pages/ProjectDetailPage/components/DeleteCheckModal.tsx
  src/pages/ProjectDetailPage/components/EmptyMessage/EmptyMessage.tsx
  src/pages/ProjectDetailPage/components/Summary/Summary.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryContent/SummaryDetail.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryContent/SummaryLeft.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryContent/SummaryLink.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryContent/SummaryLinkButton.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryContent/SummaryRight.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryContent/SwiperButton.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryTitle/SummaryTitle.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryTop/SummaryControlButton.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryTop/SummaryPopOver.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryTop/SummaryTop.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryTop/SummaryTopIcon.tsx
  src/pages/ProjectDetailPage/constants/emptyMessage.ts
  src/pages/ProjectDetailPage/styles/SwiperSlide.styles.ts
  src/routes/ScrollToTop/ScrollToTop.tsx
  src/routes/layouts/RootLayout.tsx
Labels: Refactor
