Repository side-peek/sidepeek_frontend, pull requests merged in 2024-02, with the labels that each got.

#17 [feature/#16/router] - 테스트 페이지 추가
  src/pages/TestPage/TestPage.tsx
  src/routes/index.tsx
Labels: Feat

#15 [feature/#4/error page]
  package-lock.json
  package.json
  src/App.tsx
  src/assets/images/error.gif
  src/main.tsx
  src/pages/ErrorPage/ErrorPage.tsx
  src/routes/index.tsx
  src/styles/GlobalStyles.tsx
  src/styles/fonts/SCDream4.otf
  src/styles/fonts/SCDream6.otf
  src/styles/fonts/SCDream8.otf
  src/styles/fonts/index.css
  src/styles/theme.ts
Labels: Design, Refactor

#20 [Feat ✏️] 타입 모듈 추가
  src/types/domain/apiDomain.d.ts
Labels: Feat

#18 [feature/#1/header] - 헤더 컴포넌트 구현
  package-lock.json
  package.json
  src/assets/svgs/sidepeek_logo.svg
  src/components/Header/Header.tsx
  src/components/Header/components/HeaderLogo.tsx
  src/components/Header/components/Menu.tsx
  src/components/Header/components/NotificationPopover.tsx
  src/components/Header/components/ProfilePopover.tsx
  src/routes/index.tsx
  src/styles/theme.ts
Labels: Design, Feat

#22 [feature/#13/router] - 헤더 레이아웃
  package-lock.json
  package.json
  src/routes/index.tsx
  src/styles/layouts/DefaultLayout.tsx
  tsconfig.json
Labels: Feat, Fix

#28 [Feature/#12/skill] Tag 컴포넌트 구현
  src/components/Tag/components/CloseButtonTag.tsx
  src/components/Tag/components/CustomTag.tsx
  src/components/Tag/types/customTag.ts
Labels: Design, Feat

#21 [feature/#5/ProjectCard] 프로젝트 카드 컴포넌트
  src/components/ProjectCard/ProjectCard.tsx
Labels: Design, Feat

#27 [feature/#3/Store] 전역 상태 관리 초기 설정
  src/constants/user.ts
  src/pages/TestPage/TestPage.tsx
  src/stores/authToken.ts
  src/stores/useAuthStore.ts
  src/types/domain/apiDomain.d.ts
  src/vite-env.d.ts
Labels: Feat

#26 [feature/#14/Input] Input 공용 컴포넌트 구현
  package-lock.json
  package.json
  src/components/Input/CommonInput.tsx
  src/components/Input/components/InsideElement.tsx
  src/components/Input/types/types.ts
Labels: Feat

#34 [feature/#29/msw] msw 초기 세팅
  .github/workflows/deploy.yml
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/mocks/index.ts
  src/mocks/server.ts
Labels: Feat

#46 [Hotfix/build error] build 시 public 파일 같이 빌드되는 오류 해결
  public/vite.svg
  vite.config.ts
Labels: Fix, Urgent, Minor

#43 [feature/#24/apiFunctions] 전체 api 요청 함수 구현
  src/api/auth/getEmailAuth.ts
  src/api/auth/githubLogin.ts
  src/api/auth/postEmailLogin.ts
  src/api/auth/postEmailRefresh.ts
  src/api/axiosInstance.ts
  src/api/like/postLike.ts
  src/api/project/deleteProject.ts
  src/api/project/getAllProjects.ts
  src/api/project/getProjectDetail.ts
  src/api/project/postProject.ts
  src/api/project/putProject.ts
  src/api/projectFile/postProjectFiles.ts
  src/api/skill/getSearchTechStacks.ts
  src/api/user/getUserDetail.ts
  src/api/user/getUserSummary.ts
  src/api/user/postDoubleCheckEmail.ts
  src/api/user/postDoubleCheckNickname.ts
  src/api/user/postEmailSignUp.ts
  src/api/user/putUserDetail.ts
  src/api/user/putUserPassword.ts
  src/constants/endPoints.ts
  src/constants/user.ts
  src/mocks/auth/postEmailLogin.mock.ts
  src/mocks/auth/postEmailRefresh.mock.ts
  src/mocks/handlers.ts
  src/stores/authToken.ts
  src/stores/useAuthStore.ts
  src/types/domain/apiDomain.d.ts
  src/vite-env.d.ts
Labels: Feat, Not Yet

#55 [Refactoring ⚙️] PR 모든 상황에서 액션 작동하도록 변경
  .github/workflows/deploy.yml
  src/constants/user.ts
Labels: CI/CD

#60 [ Fix] PR 작성 후 commit 추가 시 리뷰어 다시 지정되는 오류 수정
  .github/actions/reviewers/action.js
Labels: HotFix, CI/CD

#48 [Feature/#32/ ProjectDetailTop] 프로젝트 상세정보 요약정보 구현
  package-lock.json
  package.json
  src/mocks/handlers.ts
  src/pages/ProjectDetailPage/ProjectDetailPage.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailSummary.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailSummaryContent/ProjectDetailSummaryContent.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailSummaryContent/ProjectDetailSummaryLeft.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailSummaryContent/ProjectDetailSummaryLink.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailSummaryContent/ProjectDetailSummaryLinkButton.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailSummaryContent/ProjectDetailSummaryRight.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailSummaryContent/ProjectDetailSummaryRightIcon.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailSummaryContent/ProjectDetailSummaryText.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailSummaryTitle/ProjectDetailSummaryTitle.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailSummaryTop/ProjectDetailSummaryTop.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailSummaryTop/ProjectDetailSummaryTopIcon.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailSummaryTop/ProjectDetailSummaryTopIconButton.tsx
  src/pages/ProjectDetailPage/hooks/queries/useProjectDetailQuery.ts
  src/pages/ProjectDetailPage/mocks/index.ts
  src/pages/ProjectDetailPage/mocks/mockData.ts
  src/pages/ProjectDetailPage/styles/SwiperSlide.styles.ts
  src/routes/index.tsx
  src/styles/theme.ts
  src/types/domain/apiDomain.d.ts
Labels: Design, Feat, Package

#50 [Feature/#38/ProjectDetailPost] 프로젝트 상세정보 기능/트러블슈팅 탭 구현
  package-lock.json
  package.json
  src/pages/ProjectDetailPage/ProjectDetailPage.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailTabItem.tsx
  src/pages/ProjectDetailPage/components/ProjectDetailTabList.tsx
  src/pages/ProjectDetailPage/mocks/mockData.ts
  src/styles/theme.ts
  src/types/domain/apiDomain.d.ts
  vite.config.ts
Labels: Design, Feat, Package

#64 [ fix/#51/buildPerformance] 빌드 성능 개선
  .gitignore
  package-lock.json
  package.json
  src/assets/fonts/SCDream4.woff2
  src/assets/fonts/SCDream6.woff2
  src/assets/fonts/SCDream8.woff2
  src/assets/images/error.gif
  src/assets/images/error.mp4
  src/pages/ErrorPage/ErrorPage.tsx
  src/styles/fonts/SCDream4.otf
  src/styles/fonts/SCDream6.otf
  src/styles/fonts/SCDream8.otf
  src/styles/fonts/index.css
  vite.config.ts
Labels: Minor, Package
