Repository side-peek/sidepeek_frontend, pull requests merged in 2024-04, with the labels that each got.

#194 [Feature/LogoRefresh] 로고 클릭시 새로고침 실행
  src/components/LogoLink/LogoLink.tsx
Labels: Feat

#197 [refactor/#191/project detail/comment] 댓글 컴포넌트 리팩토링
  src/components/AvatarCard/AvatarCard.tsx
  src/mocks/index.ts
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/CommentsItem.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/components/CommentsAvatar.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/components/CommentsEditForm.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/components/CommentsTop/Button/BeforeEditingButton.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/components/CommentsTop/Button/OnEditingButton.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/components/CommentsTop/CommentsTop.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/components/ReplyButton.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/components/ReplyComment.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsList/CommentsList.tsx
  src/pages/ProjectDetailPage/constants/emptyMessage.ts
  src/pages/ProjectDetailPage/mocks/mockData.ts
  src/pages/ProjectDetailPage/store/CommentContext.tsx
  src/pages/ProjectDetailPage/types/commentContextProps.ts
Labels: Refactor

#201 [Refactor/ProjectDetail/Performance] 성능 개선
  index.html
  package-lock.json
  package.json
  public/robots.txt
  public/sitemap.xml
  src/App.tsx
  src/components/ MetaData/MetaData.tsx
  src/components/AvatarCard/Components/AvatarCardImage.tsx
  src/components/BackButton/BackButton.tsx
  src/components/ErrorBoundary/UncaughtErrorBoundary/components/UncaughtFallback.tsx
  src/components/Header/Header.tsx
  src/components/Header/components/Menu/components/NotificationPopover/components/NotificationIconButton.tsx
  src/components/Header/components/Menu/components/ProfilePopover/components/LogoutButton.tsx
  src/components/Header/components/Menu/components/ProfilePopover/components/ProfileButton.tsx
  src/components/ProjectCard/ProjectCard.tsx
  src/components/Tag/components/CloseButtonTag.tsx
  src/components/TechStack/TechStackSection.tsx
  src/mocks/index.ts
  src/pages/HomePage/HomePage.tsx
  src/pages/LoginPage/components/SocialLogin.tsx
  src/pages/ProfileEditPage/components/Modal/ChangeProfileImageModal.tsx
  src/pages/ProfileEditPage/components/Profile/ProfileCard.tsx
  src/pages/ProfileEditPage/components/Profile/ProfileIntroduction.tsx
  src/pages/ProfilePage/components/Profile/ProfileIntroduction.tsx
  src/pages/ProjectDetailPage/ProjectDetailPage.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsForm/CommentsForm.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/components/CommentsAvatar.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/components/CommentsTop/Button/BeforeEditingButton.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/components/CommentsTop/Button/OnEditingButton.tsx
  src/pages/ProjectDetailPage/components/Comments/CommentsItem/components/CommentsTop/CommentsTop.tsx
  src/pages/ProjectDetailPage/components/Content/Explanation/Explanation.tsx
  src/pages/ProjectDetailPage/components/Content/TechStacks/TechStacks.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryContent/SummaryLink.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryContent/SummaryRight.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryTop/SummaryPopOver.tsx
  src/pages/ProjectDetailPage/components/Summary/SummaryTop/SummaryTop.tsx
  src/pages/ProjectDetailPage/constants/scrollBarNone.ts
  src/pages/ProjectDetailPage/mocks/mockData.ts
  src/pages/ProjectEditPage/components/Files/FileUploadBox.tsx
  src/pages/ProjectEditPage/components/MemberFields/components/MemberAvatarCard.tsx
  src/pages/ProjectEditPage/components/styles/CloseButton.tsx
  src/pages/ProjectListPage/components/SearchBarSection/SearchBarSection.tsx
  src/pages/SignUpPage/components/SignUpForm/components/DoubleCheckButton.tsx
  src/pages/SignUpPage/components/SocialSignUp.tsx
  src/routes/index.tsx
  src/routes/layouts/DefaultLayout.tsx
  src/routes/layouts/RootLayout.tsx
  vite.config.ts
Labels: Refactor

#204 [Refactor/#201/project detail/performance2] 검색엔진 오류 수정
  index.html
  robots.txt
Labels: HotFix

#208 [Fix 🪛] 확장자 오류 수정
  src/components/ProjectCard/ProjectCard.tsx
  src/pages/HomePage/components/Banner/Banner.tsx
Labels: HotFix

#210 [Remove 🗑️] publicDir옵션 삭제
  vite.config.ts
Labels: HotFix

#212 [refactor/#211/performance] - 메타태그 오류 수정
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/components/ MetaData/MetaData.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/ProjectDetailPage/ProjectDetailPage.tsx
  src/pages/ProjectDetailPage/components/Content/TechStacks/TechStacks.tsx
  src/routes/layouts/DefaultLayout.tsx
Labels: Refactor
